
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\ItemHandler\ItemHandlerInterface:
            tags: ['app.item_handler']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\DefaultController:
        $itemHandlersIterable:       !tagged 'app.item_handler'
        $itemHandlersLocatorByClass: !tagged_locator { tag: 'app.item_handler' }
        $itemHandlersLocatorByKey:   !tagged_locator { tag: 'app.item_handler', default_index_method: 'getDefaultIndexName'}

    App\ItemHandler\ItemHandlersLocator:
        arguments:
            - !tagged_locator { tag: 'app.item_handler', default_index_method: 'getDefaultIndexName'}